{
 "title": "farming_dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "All sensors state timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_humidity\" or r[\"_measurement\"] == \"farm_moisture\" or r[\"_measurement\"] == \"farm_sunlight\" or r[\"_measurement\"] == \"farm_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity_farm1\" or r[\"_field\"] == \"humidity_farm2\" or r[\"_field\"] == \"humidity_farm3\" or r[\"_field\"] == \"moisture_farm1\" or r[\"_field\"] == \"moisture_farm2\" or r[\"_field\"] == \"moisture_farm3\" or r[\"_field\"] == \"sunlight_farm1\" or r[\"_field\"] == \"sunlight_farm2\" or r[\"_field\"] == \"sunlight_farm3\" or r[\"_field\"] == \"temperature_farm1\" or r[\"_field\"] == \"temperature_farm2\" or r[\"_field\"] == \"temperature_farm3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Farm 1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_humidity\" or r[\"_measurement\"] == \"farm_moisture\" or r[\"_measurement\"] == \"farm_sunlight\" or r[\"_measurement\"] == \"farm_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity_farm1\" or r[\"_field\"] == \"moisture_farm1\" or r[\"_field\"] == \"sunlight_farm1\" or r[\"_field\"] == \"temperature_farm1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Farm 2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_humidity\" or r[\"_measurement\"] == \"farm_moisture\" or r[\"_measurement\"] == \"farm_sunlight\" or r[\"_measurement\"] == \"farm_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity_farm2\" or r[\"_field\"] == \"moisture_farm2\" or r[\"_field\"] == \"sunlight_farm2\" or r[\"_field\"] == \"temperature_farm2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Farm 3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_humidity\" or r[\"_measurement\"] == \"farm_moisture\" or r[\"_measurement\"] == \"farm_sunlight\" or r[\"_measurement\"] == \"farm_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity_farm3\" or r[\"_field\"] == \"moisture_farm3\" or r[\"_field\"] == \"sunlight_farm3\" or r[\"_field\"] == \"temperature_farm3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity Bar Gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_humidity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity_farm1\" or r[\"_field\"] == \"humidity_farm2\" or r[\"_field\"] == \"humidity_farm3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Moisture bar gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_moisture\")\n  |> filter(fn: (r) => r[\"_field\"] == \"moisture_farm1\" or r[\"_field\"] == \"moisture_farm2\" or r[\"_field\"] == \"moisture_farm3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sunlight bar gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_sunlight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sunlight_farm1\" or r[\"_field\"] == \"sunlight_farm2\" or r[\"_field\"] == \"sunlight_farm3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature bar gauge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_farm1\" or r[\"_field\"] == \"temperature_farm2\" or r[\"_field\"] == \"temperature_farm3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}